# Generated by Django 4.2.7 on 2023-12-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cardmodel_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
