# Generated by Django 4.2.7 on 2023-12-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brandmodel_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(max_length=500, null=True, unique=True),
        ),
    ]
